"""
OCR helpers.

Runs Tesseract (via pytesseract) on PDF pages that don't already carry a
usable text layer. Produces:

  * a *searchable PDF* – original vector pages are kept as-is, pages that
    had to be OCR'd are replaced with an image+invisible-text layer page
    generated by `pytesseract.image_to_pdf_or_hocr`.
  * a plain-text transcript per processed page.

Jobs run in a background thread so the browser can poll for progress.

External dependencies (detected at runtime, clear errors if missing):
    - tesseract (system), reachable through `pytesseract`
    - poppler-utils (for pdf2image to rasterise PDF pages)
    - pytesseract, pdf2image, Pillow (pip)
"""

from __future__ import annotations

import io
import os
import re
import threading
import time
import jobs

from PyPDF2 import PdfReader, PdfWriter
# ---------------------------------------------------------------------------
# Page-range parsing – now lives in pageselect.py (it was never OCR-specific).
# Re-exported here so existing callers keep working.
# ---------------------------------------------------------------------------
from pageselect import parse_page_range  # noqa: E402,F401

# pytesseract pulls in PIL plumbing and probes the tesseract binary, which is
# slow at import time. Load it on first use instead so start-up stays fast.
pytesseract = None
_PYT_STATE = None


def _ensure_pytesseract() -> bool:
    global pytesseract, _PYT_STATE
    if _PYT_STATE is None:
        try:
            import pytesseract as _p
            pytesseract = _p
            _PYT_STATE = True
        except Exception:
            _PYT_STATE = False
    return _PYT_STATE

try:
    from PIL import Image   # noqa: F401
    _HAS_PIL = True
except Exception:
    _HAS_PIL = False

try:
    from pdf2image import convert_from_path
    _HAS_P2I = True
except Exception:
    convert_from_path = None
    _HAS_P2I = False


class OCRError(Exception):
    """Raised for any OCR-related failure that should surface to the user."""


# ---------------------------------------------------------------------------
# Languages
# ---------------------------------------------------------------------------
LANGUAGE_LABELS = {
    'eng':     'English',
    'chi_sim': 'Chinese (Simplified)',
    'chi_tra': 'Chinese (Traditional)',
    'jpn':     'Japanese',
    'kor':     'Korean',
    'spa':     'Spanish',
    'fra':     'French',
    'deu':     'German',
}
AUTO_CODE = 'auto'


def tesseract_available() -> bool:
    if not (_ensure_pytesseract() and _HAS_PIL):
        return False
    try:
        pytesseract.get_tesseract_version()
        return True
    except Exception:
        return False


def poppler_available() -> bool:
    return _HAS_P2I


def available_languages() -> dict:
    """Return {code: label} for the supported languages that are installed."""
    if not tesseract_available():
        return {}
    try:
        installed = set(pytesseract.get_languages(config=''))
    except Exception:
        return {}
    return {c: l for c, l in LANGUAGE_LABELS.items() if c in installed}


def _resolve_language(lang: str) -> str:
    avail = available_languages()
    if not avail:
        raise OCRError(
            'No supported OCR language data is installed. Install Tesseract language '
            'packs (e.g. tesseract-ocr-eng, tesseract-ocr-chi-sim) and restart.')
    if lang == AUTO_CODE:
        return '+'.join(avail.keys())
    if lang not in avail:
        raise OCRError(f'OCR language "{lang}" is not installed on the server.')
    return lang


def has_text_layer(page, min_chars: int = 30) -> bool:
    """True when a PDF page already has enough selectable text to skip OCR."""
    try:
        text = page.extract_text() or ''
    except Exception:
        text = ''
    return sum(1 for ch in text if not ch.isspace()) >= min_chars
    """Turn '1-3,5,7-8' into a sorted unique list of valid page numbers."""
    spec = (spec or '').strip()
    if not spec:
        raise OCRError('Page range is empty.')
    pages: set[int] = set()
    for token in re.split(r'[\s,]+', spec):
        if not token:
            continue
        m = re.match(r'^(\d+)-(\d+)$', token)
        if m:
            a, b = int(m.group(1)), int(m.group(2))
            if a < 1 or b < 1 or a > b:
                raise OCRError(f'Invalid range "{token}".')
            for p in range(a, b + 1):
                if 1 <= p <= total:
                    pages.add(p)
        elif token.isdigit():
            p = int(token)
            if 1 <= p <= total:
                pages.add(p)
        else:
            raise OCRError(f'Invalid page range token "{token}".')
    if not pages:
        raise OCRError('Page range matched no valid pages.')
    return sorted(pages)


# ---------------------------------------------------------------------------
# Job registry (shared implementation – see jobs.py)
# ---------------------------------------------------------------------------
_REGISTRY = jobs.JobRegistry({
    'total': 0,
    'processed': 0,
    'current_page': 0,
    'pages': [],            # per-page text, filled when done
    'pdf_name': None,
    'txt_name': None,
})


def new_job() -> str:
    return _REGISTRY.new()


def get_job(jid: str):
    return _REGISTRY.get(jid)


def cancel_job(jid: str) -> bool:
    return _REGISTRY.cancel(jid)


_patch = _REGISTRY.patch
_is_cancelled = _REGISTRY.is_cancelled


# ---------------------------------------------------------------------------
# Worker
# ---------------------------------------------------------------------------
def start_ocr_job(jid: str, src_pdf_path: str, pages_to_process: list[int],
                  lang: str, generated_dir: str, base_name: str = 'ocr',
                  cleanup_path: str | None = None) -> None:
    """Kick off the worker thread. Non-blocking."""
    t = threading.Thread(
        target=_worker,
        args=(jid, src_pdf_path, list(pages_to_process), lang, generated_dir,
              base_name, cleanup_path),
        daemon=True,
    )
    t.start()


def _worker(jid, src_pdf_path, pages_to_process, lang, generated_dir, base_name,
            cleanup_path=None):
    try:
        if not tesseract_available():
            raise OCRError(
                'Tesseract is not available on the server. On Debian/Ubuntu: '
                'apt install tesseract-ocr tesseract-ocr-eng.')
        if not poppler_available():
            raise OCRError(
                'pdf2image / poppler is not available on the server. Install '
                'poppler-utils and `pip install pdf2image`.')

        lang_code = _resolve_language(lang)

        reader = PdfReader(src_pdf_path)
        total_pages = len(reader.pages)
        if total_pages == 0:
            raise OCRError('The PDF has no pages.')

        target = sorted({p for p in pages_to_process if 1 <= p <= total_pages})
        if not target:
            raise OCRError('No valid pages were selected for OCR.')

        _patch(jid,
               status='running',
               total=len(target),
               processed=0,
               message=f'Starting OCR on {len(target)} page(s)…')

        writer = PdfWriter()
        page_texts: list[dict] = []
        done = 0

        for page_num in range(1, total_pages + 1):
            if _is_cancelled(jid):
                raise OCRError('Cancelled by user.')

            page = reader.pages[page_num - 1]

            if page_num not in target:
                writer.add_page(page)
                continue

            if has_text_layer(page):
                writer.add_page(page)
                try:
                    txt = page.extract_text() or ''
                except Exception:
                    txt = ''
                page_texts.append({
                    'page': page_num, 'text': txt,
                    'from_layer': True, 'skipped_ocr': True,
                })
                done += 1
                _patch(jid, processed=done, current_page=page_num,
                       progress=int(done * 100 / len(target)),
                       message=f'Page {page_num}: used existing text layer ({done}/{len(target)})')
                continue

            _patch(jid, current_page=page_num, message=f'Rendering page {page_num}…')
            try:
                imgs = convert_from_path(src_pdf_path, dpi=200,
                                         first_page=page_num, last_page=page_num)
            except Exception as e:
                raise OCRError(f'Could not render page {page_num}: {e}')
            if not imgs:
                raise OCRError(f'No image produced for page {page_num}.')
            img = imgs[0]

            _patch(jid, message=f'OCR page {page_num}…')
            try:
                ocr_text = pytesseract.image_to_string(img, lang=lang_code) or ''
                ocr_pdf = pytesseract.image_to_pdf_or_hocr(img, extension='pdf', lang=lang_code)
            except Exception as e:
                raise OCRError(f'Tesseract failed on page {page_num}: {e}')

            try:
                sub_reader = PdfReader(io.BytesIO(ocr_pdf))
                if sub_reader.pages:
                    writer.add_page(sub_reader.pages[0])
                else:
                    writer.add_page(page)
            except Exception:
                writer.add_page(page)

            page_texts.append({
                'page': page_num, 'text': ocr_text,
                'from_layer': False, 'skipped_ocr': False,
            })
            done += 1
            _patch(jid, processed=done, current_page=page_num,
                   progress=int(done * 100 / len(target)),
                   message=f'Completed page {page_num} ({done}/{len(target)})')

        safe_base = re.sub(r'[^A-Za-z0-9._-]+', '_', base_name or 'ocr')[:40] or 'ocr'
        pdf_name = f'ocr_{jid}_{safe_base}.pdf'
        txt_name = f'ocr_{jid}_{safe_base}.txt'
        pdf_path = os.path.join(generated_dir, pdf_name)
        txt_path = os.path.join(generated_dir, txt_name)

        os.makedirs(generated_dir, exist_ok=True)
        with open(pdf_path, 'wb') as fh:
            writer.write(fh)
        with open(txt_path, 'w', encoding='utf-8') as fh:
            for pt in page_texts:
                fh.write(f'--- Page {pt["page"]}')
                if pt['from_layer']:
                    fh.write(' (existing text layer)')
                fh.write(' ---\n')
                fh.write(pt['text'].rstrip())
                fh.write('\n\n')

        _patch(jid,
               status='done',
               progress=100,
               pdf_name=pdf_name,
               txt_name=txt_name,
               pages=page_texts,
               finished_at=time.time(),
               message=f'OCR complete. {len(target)} page(s) processed.')
    except OCRError as e:
        _REGISTRY.fail(jid, str(e), 'Cancelled. No output was produced.')
    except Exception as e:                  # pragma: no cover
        _REGISTRY.fail(jid, f'Unexpected error: {e}',
                       'Cancelled. No output was produced.')
    finally:
        jobs.discard(cleanup_path)